In [3]:
import pandas as pd
import numpy as np
import seaborn as snsz

In [4]:
k=[4,6,2.5686,9,6.525,'hyderabad']
k

[4, 6, 2.5686, 9, 6.525, 'hyderabad']

In [7]:
pd.Series(k)

0            4
1            6
2       2.5686
3            9
4        6.525
5    hyderabad
dtype: object

In [9]:
a=np.random.randint(20,50,(5,4))
a

array([[30, 32, 23, 33],
       [38, 26, 48, 26],
       [34, 43, 38, 44],
       [28, 22, 39, 39],
       [45, 24, 39, 46]])

In [33]:
b=np.random.randint(5,68,15)
b

array([11, 65, 27, 15, 24, 23, 66, 42, 36, 55, 59, 18, 65, 45, 31])

In [35]:
pd.Series(b)





0     11
1     65
2     27
3     15
4     24
5     23
6     66
7     42
8     36
9     55
10    59
11    18
12    65
13    45
14    31
dtype: int32

In [37]:
 b.ndim

1

In [39]:
b.shape

(15,)

In [43]:
c=np.random.randint(5,68,(8,4))
c

array([[ 8, 25, 45, 41],
       [17, 57, 33, 51],
       [24, 67, 53, 37],
       [59, 63, 42, 10],
       [63, 10, 12, 66],
       [26, 30, 44, 65],
       [53, 56, 56, 60],
       [ 6, 42, 62, 23]])

In [29]:
c.ndim

2

In [31]:
c.shape

(12, 4)

In [51]:
df=pd.DataFrame(c)
df

0   1   2   3
0   8  25  45  41
1  17  57  33  51
2  24  67  53  37
3  59  63  42  10
4  63  10  12  66
5  26  30  44  65
6  53  56  56  60
7   6  42  62  23

In [55]:
h=pd.DataFrame(c,columns=['Roll','Name','Age','Country'])
h

Roll  Name  Age  Country
0     8    25   45       41
1    17    57   33       51
2    24    67   53       37
3    59    63   42       10
4    63    10   12       66
5    26    30   44       65
6    53    56   56       60
7     6    42   62       23

In [73]:
j=pd.DataFrame(c,index=[10,20,30,40,50,60,70,80])
j

0   1   2   3
10   8  25  45  41
20  17  57  33  51
30  24  67  53  37
40  59  63  42  10
50  63  10  12  66
60  26  30  44  65
70  53  56  56  60
80   6  42  62  23

In [75]:
i=pd.DataFrame(c,columns=['Roll','Name','Age','Country'],index=[10,20,30,40,50,60,70,80])
i

Roll  Name  Age  Country
10     8    25   45       41
20    17    57   33       51
30    24    67   53       37
40    59    63   42       10
50    63    10   12       66
60    26    30   44       65
70    53    56   56       60
80     6    42   62       23

In [79]:
i.iloc[3]

Roll       59
Name       63
Age        42
Country    10
Name: 40, dtype: int32